[package]
name = "drpa-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "drpa_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
drpa-host = { path = "../../../crates/drpa-host" }
drpa-protocol = { path = "../../../crates/drpa-protocol" }
serde.workspace = true
tauri = { version = "2", features = [] }
